name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  dependencies: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Build with Maven
        env:
          S_USERNAME: ${{ secrets.S_USERNAME }}
          S_PASSWORD: ${{ secrets.S_PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}
          CI_RUN: true
        run: mvn -B package --file pom.xml
      - name: Run all Tests (TestNG and JUnit)
        run: mvn test
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      - name: Display Test Results
        run: cat target/surefire-reports/*.txt || true
      - name: Attach screenshots and reports
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: screenshots-and-report
          path: |
            screenshots
            target/surefire-reports/emailable-report.html
      - name: Attach reports only
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: target/surefire-reports/emailable-report.html
